name: Keychain & Certificate
description: |
  Setup the macOS Keychain with P12 Certificate
inputs:
  certificate-base64:
    description: A P12 Certificate which has been encoded using base64.
    type: string
    required: true
  certificate-password:
    description: The password which is used to unlock the Certificate.
    type: string
    required: true
  keychain-password:
    description: Password which will be associated with the keychain. (Any Value)
    type: string
    required: true
runs:
  using: "composite"
  steps:
  - name: Setup Keychain
    shell: bash
    run: |
      CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12
      KEYCHAIN_PATH=$RUNNER_TEMP/certificate.keychain-db
      echo -n "${{ secrets.certificate-base64 }}" | base64 -decode -o $CERTIFICATE_PATH
      security create-keychain -p "${{ secrets.keychain-password }}"
      security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
      security unlock-keychain -p "${{ secrets.keychain-password }}" $KEYCHAIN_PATH
      security import $CERTIFICATE_PATH -P "${{ secrets.certificate-password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      security set-key-partition-list -S apple-tool:,apple: -k "${{ secrets.keychain-password }}" $KEYCHAIN_PATH
      security list-keychain -d user -s $KEYCHAIN_PATH
