name: Provisioning Profile
description: |
  Install a provisioning profile that will be used for app signing.
inputs:
  profile-base64:
    description: A profile which has been encoded using base64.
    type: string
    required: true
  platform:
    description: Platform that will be used during the build/signing/archiving tasks.
    type: string
    required: true
    default: 'iOS'
runs:
  using: "composite"
  steps:
  - name: Install Profile (iOS)
    if: ${{ inputs.platform != 'macOS' }}
    shell: bash
    env:
      EXTENSION: 'mobileprovision'
      PROFILES_PATH: '~/Library/Developer/Xcode/UserData/Provisioning Profiles/'
    run: |
      PROFILE_PATH=$RUNNER_TEMP/provision.$EXTENSION
      echo -n "${{ inputs.profile-base64 }}" | base64 --decode -o $PROFILE_PATH
      mkdir -p $PROFILES_PATH
      mv $PROFILE_PATH $PROFILES_PATH
  - name: Install Profile (macOS)
    if: ${{ inputs.platform == 'macOS' }}
    shell: bash
    env:
      EXTENSION: 'provisionprofile'
      PROFILES_PATH: '~/Library/Developer/Xcode/UserData/Provisioning Profiles/'
    run: |
      PROFILE_PATH=$RUNNER_TEMP/provision.$EXTENSION
      echo -n "${{ inputs.profile-base64 }}" | base64 --decode -o $PROFILE_PATH
      mkdir -p $PROFILES_PATH
      mv $PROFILE_PATH $PROFILES_PATH
